name: CampfireAnyplace
version: '1.0.1'
main: dev.campfireanyplace.CampfireAnyplacePlugin
api-version: '1.13'
description: Put any item on a campfire while preserving campfire block item contents.
author: CampfireAnyplace
