name: CampfireAnyplace
version: '1.2.0'
main: dev.campfireanyplace.CampfireAnyplacePlugin
api-version: '1.13'
description: Put any item on regular and soul campfires while preserving their contents.
author: CampfireAnyplace
